### ISSUE TITLE
Fauna free plan limit reached for this month

### ISSUE THREAD

**Issue by ghost** [mtamc/memo#42]
I temporarily upgraded to the Individual ($25/month) plan and put my card on it, here's the breakdown:

- Free plan has a maximum of 100k "read ops", 50k write ops per month
- This month we're at 4m3 read ops ($1.70 over 100k) and 107k write ops ($0.12 over 50k)
- Quick maths estimate that at the current usage we're spending $9 a month which is within the $25 Individual plan limit...for now

Points to expressly consider
- "Lazily" retrieving reviews (i.e. when unfolded) might cut resource usage by at least 10 ("read ops" are measured in document size), this should probably be the first thing to address
- Is FaunaDB's model right for our use case?
- Should we move to another system, if so, what?
- Unfortunately, I'm not able to project the cost of different database solutions

**Comment by mtamc** [comment]
I think this has been fixed by migrating to free MongoDB.
