### ISSUE TITLE
Can't overwrite game title

### ISSUE THREAD

**Issue by dustinvtran** [mtamc/memo#69]
Overwriting "Titan Quest: Gold Edition" title name to be "Titan Quest" seems to just revert the title back to "Titan Quest: Gold Edition".  Not sure why this happens.

![2023-04-02 01_13_40](https://user-images.githubusercontent.com/2569867/229340850-77ec7429-1512-4a5a-80e1-3ceb330e915e.png)

**Comment by tam-carre** [comment]
received, will fix soon, maybe today depending on my day job

**Comment by tam-carre** [comment]
Didn't find the problem, but for now I changed the title manually, let me know if it happens for any other field/entry

**Comment by dustinvtran** [comment]
if you're trying to reproduce, it takes a while for the title to reset if
you manually overwrite it in the UI. would need to wait like 30 mins or
something

**Comment by tam-carre** [comment]
oh ok i have reproduced the issue, it happens when editing the entry a
second time, will make a fix

**Comment by tam-carre** [comment]
14332f7 fixed
