### ISSUE TITLE
Video game entries added never have an HLTB entry

### ISSUE THREAD

**Issue by dustinvtran** [mtamc/memo#71]
Whenever I add a video game entry, I never see the "Duration" entry appear. For some reason, the added entries never include the HLTB ID.

**Comment by dustinvtran** [comment]
Since so many entries don't include an HLTB ID, it might be helpful to also do a crawl through the database and join the existing entries with any HLTB ID it finds.

If you have pointers for how I might do this (any scripts or code you've done for this before), let me know. I'm happy to help so that you don't need to be bothered with all my various requests. :-)

**Comment by mtamc** [comment]
The HLTB fetcher seems functional in production, let me know if it breaks again.
I've filled in all missing game duration values in the database, and I added the script I used for this in [ba5ef65](https://github.com/mtamc/memo/commit/ba5ef659bfe0bbe571319010d2402d8068b1515d)
