### ISSUE TITLE
Entries not always saving edits

### ISSUE THREAD

**Issue by dustinvtran** [mtamc/memo#72]
In particular, editing "Diablo IV" entry doesn't always save the new information. This caused me to lose edits a few times today.

Hasn't happened until today. Possibly a transient or database issue? What's the best practice to avoid this?

**Comment by dustinvtran** [comment]
Oh, seems to happen in TV entries too. So perhaps a database issue overall.

Related: I'm also seeing Error: 500 when loading lists.

**Comment by mtamc** [comment]
Cannot reproduce the unsaved edits or the 500 at the moment, next time you get a 500 can you try to reproduce with devtools open and see what if the 500-returning request offers any additional information.

**Comment by mtamc** [comment]
Hasn't happened in a while, closing for now
