### ISSUE TITLE
Can't remove year in entries

### ISSUE THREAD

**Issue by dustinvtran** [mtamc/memo#73]
For example, setting Squid Game from year 2021 to blank (in order to mark Season 2 separately) resets to year 2021.

**Comment by mtamc** [comment]
As of [5228f2e](https://github.com/mtamc/memo/commit/5228f2efdd9c33392c8bff070223425b6b9d2352), setting the release year to an empty field replaces the database's value with null, this is deploying now. Let me know if there are any issues.
