### ISSUE TITLE
Add publisher metadata to books

### ISSUE THREAD

**Issue by dustinvtran** [mtamc/memo#75]
This is helpful, for example, to search for entries by prominent publishers like Tor, Titan, Marvel Comics, DC Comics, etc.

**Comment by mtamc** [comment]
done in ea6da57
deploying, let me know if there are any issues
A script is currently running slowly adding missing publisher data to existing works, might take a few hours to complete (i set a generous delay between updates due to Google rate limits, probably very unoptimized but it's okay)
